# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 14:51


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UNLAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('streetaddress1', models.CharField(blank=True, max_length=765)),
                ('streetaddress2', models.CharField(blank=True, max_length=765)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, max_length=6)),
                ('zip', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('fax', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('accountstatus', models.CharField(blank=True, max_length=300)),
                ('datecreated', models.DateTimeField(blank=True, null=True)),
                ('datelastupdated', models.DateTimeField(blank=True, null=True)),
                ('sponsor_id', models.IntegerField()),
                ('website', models.CharField(blank=True, max_length=765)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='UNLAdmissioncharge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('admissioninfogroup_id', models.IntegerField()),
                ('price', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=765)),
            ],
            options={
                'db_table': 'admissioncharge',
            },
        ),
        migrations.CreateModel(
            name='UNLAdmissioninfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=765)),
                ('obligation', models.CharField(blank=True, max_length=300)),
                ('contactname', models.CharField(blank=True, max_length=300)),
                ('contactphone', models.CharField(blank=True, max_length=150)),
                ('contactemail', models.CharField(blank=True, max_length=765)),
                ('contacturl', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=765)),
                ('additionalinfo', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('opendate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admissioninfo',
            },
        ),
        migrations.CreateModel(
            name='UNLAttendancerestriction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendancerestriction',
            },
        ),
        migrations.CreateModel(
            name='UNLAudience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('standard', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audience',
            },
        ),
        migrations.CreateModel(
            name='UNLCalendar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=765)),
                ('shortname', models.CharField(blank=True, max_length=300)),
                ('website', models.CharField(blank=True, max_length=765)),
                ('recommendationswithinaccount', models.IntegerField(blank=True, null=True)),
                ('eventreleasepreference', models.CharField(blank=True, max_length=765)),
                ('calendardaterange', models.IntegerField(blank=True, null=True)),
                ('formatcalendardata', models.TextField(blank=True)),
                ('uploadedcss', models.TextField(blank=True)),
                ('uploadedxsl', models.TextField(blank=True)),
                ('emaillists', models.TextField(blank=True)),
                ('calendarstatus', models.CharField(blank=True, max_length=765)),
                ('datecreated', models.DateTimeField(blank=True, null=True)),
                ('uidcreated', models.CharField(blank=True, max_length=765)),
                ('datelastupdated', models.DateTimeField(blank=True, null=True)),
                ('uidlastupdated', models.CharField(blank=True, max_length=765)),
                ('externalforms', models.CharField(blank=True, max_length=765)),
            ],
            options={
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='UNLCalendarHasEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calendar_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=300)),
                ('datecreated', models.DateTimeField(blank=True, null=True)),
                ('uidcreated', models.CharField(blank=True, max_length=300)),
                ('datelastupdated', models.DateTimeField(blank=True, null=True)),
                ('uidlastupdated', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'calendar_has_event',
            },
        ),
        migrations.CreateModel(
            name='UNLDocument',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=765)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='UNLEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('othereventtype', models.CharField(blank=True, max_length=765)),
                ('description', models.TextField(blank=True)),
                ('shortdescription', models.CharField(blank=True, max_length=765)),
                ('refreshments', models.CharField(blank=True, max_length=765)),
                ('classification', models.CharField(blank=True, max_length=300)),
                ('approvedforcirculation', models.IntegerField(blank=True, null=True)),
                ('transparency', models.CharField(blank=True, max_length=765)),
                ('status', models.CharField(blank=True, max_length=300)),
                ('privatecomment', models.TextField(blank=True)),
                ('otherkeywords', models.CharField(blank=True, max_length=765)),
                ('imagetitle', models.CharField(blank=True, max_length=300)),
                ('imageurl', models.TextField(blank=True)),
                ('webpageurl', models.TextField(blank=True)),
                ('listingcontactuid', models.CharField(blank=True, max_length=765)),
                ('listingcontactname', models.CharField(blank=True, max_length=300)),
                ('listingcontactphone', models.CharField(blank=True, max_length=765)),
                ('listingcontactemail', models.CharField(blank=True, max_length=765)),
                ('icalendar', models.TextField(blank=True)),
                ('imagedata', models.TextField(blank=True)),
                ('imagemime', models.CharField(blank=True, max_length=765)),
                ('datecreated', models.DateTimeField(blank=True, null=True)),
                ('uidcreated', models.CharField(blank=True, max_length=300)),
                ('datelastupdated', models.DateTimeField(blank=True, null=True)),
                ('uidlastupdated', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='UNLEventdatetime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=765)),
                ('hours', models.CharField(blank=True, max_length=765)),
                ('directions', models.TextField(blank=True)),
                ('additionalpublicinfo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'eventdatetime',
            },
        ),
        migrations.CreateModel(
            name='UNLEventHasEventtype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('eventtype_id', models.IntegerField()),
            ],
            options={
                'db_table': 'event_has_eventtype',
            },
        ),
        migrations.CreateModel(
            name='UNLEventHasKeyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('keyword_id', models.IntegerField()),
            ],
            options={
                'db_table': 'event_has_keyword',
            },
        ),
        migrations.CreateModel(
            name='UNLEventHasSponsor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('sponsor_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_has_sponsor',
            },
        ),
        migrations.CreateModel(
            name='UNLEventIsopentoAudience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('audience_id', models.IntegerField()),
            ],
            options={
                'db_table': 'event_isopento_audience',
            },
        ),
        migrations.CreateModel(
            name='UNLEventTargetsAudience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('audience_id', models.IntegerField()),
            ],
            options={
                'db_table': 'event_targets_audience',
            },
        ),
        migrations.CreateModel(
            name='UNLEventtype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calendar_id', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=765)),
                ('eventtypegroup', models.CharField(blank=True, max_length=24)),
                ('standard', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventtype',
            },
        ),
        migrations.CreateModel(
            name='UNLKeyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='UNLLocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('streetaddress1', models.CharField(blank=True, max_length=765)),
                ('streetaddress2', models.CharField(blank=True, max_length=765)),
                ('room', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, max_length=6)),
                ('zip', models.CharField(blank=True, max_length=30)),
                ('mapurl', models.TextField(blank=True)),
                ('webpageurl', models.TextField(blank=True)),
                ('hours', models.CharField(blank=True, max_length=765)),
                ('directions', models.TextField(blank=True)),
                ('additionalpublicinfo', models.CharField(blank=True, max_length=765)),
                ('type', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='UNLPerformer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('performer_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('personalname', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(blank=True, max_length=765)),
                ('jobtitle', models.CharField(blank=True, max_length=300)),
                ('organizationname', models.CharField(blank=True, max_length=300)),
                ('personalwebpageurl', models.TextField(blank=True)),
                ('organizationwebpageurl', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=765)),
            ],
            options={
                'db_table': 'performer',
            },
        ),
        migrations.CreateModel(
            name='UNLPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=765)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='UNLPubliccontact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=300)),
                ('jobtitle', models.CharField(blank=True, max_length=300)),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('addressline1', models.CharField(blank=True, max_length=765)),
                ('addressline2', models.CharField(blank=True, max_length=765)),
                ('room', models.CharField(blank=True, max_length=765)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, max_length=6)),
                ('zip', models.CharField(blank=True, max_length=30)),
                ('emailaddress', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('fax', models.CharField(blank=True, max_length=150)),
                ('webpageurl', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'publiccontact',
            },
        ),
        migrations.CreateModel(
            name='UNLRelatedevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('related_event_id', models.IntegerField()),
                ('relationtype', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'relatedevent',
            },
        ),
        migrations.CreateModel(
            name='UNLRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=765)),
                ('standard', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UNLSession',
            fields=[
                ('user_uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lastaction', models.DateTimeField()),
                ('data', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='UNLSponsor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=765)),
                ('standard', models.IntegerField(blank=True, null=True)),
                ('sponsortype', models.CharField(blank=True, max_length=765)),
                ('webpageurl', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sponsor',
            },
        ),
        migrations.CreateModel(
            name='UNLSubscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calendar_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=300)),
                ('automaticapproval', models.IntegerField()),
                ('timeperiod', models.DateField(blank=True, null=True)),
                ('expirationdate', models.DateField(blank=True, null=True)),
                ('searchcriteria', models.TextField(blank=True)),
                ('datecreated', models.DateTimeField(blank=True, null=True)),
                ('uidcreated', models.CharField(blank=True, max_length=300)),
                ('datelastupdated', models.DateTimeField(blank=True, null=True)),
                ('uidlastupdated', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='UNLTestTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
        migrations.CreateModel(
            name='UNLUser',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('calendar_id', models.IntegerField(blank=True, null=True)),
                ('accountstatus', models.CharField(blank=True, max_length=300)),
                ('datecreated', models.DateTimeField(blank=True, null=True)),
                ('uidcreated', models.CharField(blank=True, max_length=300)),
                ('datelastupdated', models.DateTimeField(blank=True, null=True)),
                ('uidlastupdated', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UNLUserHasPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission_id', models.IntegerField()),
                ('user_uid', models.CharField(max_length=300)),
                ('calendar_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_has_permission',
            },
        ),
        migrations.CreateModel(
            name='UNLWebcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(blank=True, max_length=300)),
                ('dateavailable', models.DateTimeField(blank=True, null=True)),
                ('playertype', models.CharField(blank=True, max_length=300)),
                ('bandwidth', models.CharField(blank=True, max_length=765)),
                ('additionalinfo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'webcast',
            },
        ),
        migrations.CreateModel(
            name='UNLWebcastlink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('webcast_id', models.IntegerField()),
                ('url', models.TextField(blank=True)),
                ('sequencenumber', models.IntegerField(blank=True, null=True)),
                ('related', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'db_table': 'webcastlink',
            },
        ),
    ]
