# Generated by Django 3.1.1 on 2020-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'posted')], default=1),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='interval',
            field=models.SmallIntegerField(choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (3, 'Biweekly'), (4, 'Monthly'), (5, 'Yearly')], default=0),
        ),
    ]
