# Generated by Django 3.1.1 on 2020-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200914_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='virtual_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
