# Generated by Django 3.1.1 on 2020-12-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventinstance_virtual_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
