# Generated by Django 3.1.1 on 2021-02-04 14:16

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events', '0005_calendar_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoted', to='taggit.tag')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='events.PromotedTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
