# Generated by Django 3.1.1 on 2021-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210208_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
