# Generated by Django 3.1.14 on 2022-11-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210211_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='internal_link_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
