# Generated by Django 3.1.14 on 2022-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210211_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
