# Generated by Django 3.1.14 on 2022-11-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_internal_link_checked'),
        ('events', '0010_promotion'),
    ]

    operations = [
    ]
