# Generated by Django 3.1.14 on 2025-05-08 14:01

from django.db import migrations, models
from django.conf import settings

def forward_migration(apps, schema_editor):
    Calendar = apps.get_model('events', 'Calendar')
    if settings.FRONT_PAGE_CALENDAR_PK:
        try:
            main_calendar = Calendar.objects.get(pk=settings.FRONT_PAGE_CALENDAR_PK)
            main_calendar.tier = 1
            main_calendar.save()
        except:
            pass

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=3),
        ),
        migrations.RunPython(forward_migration, reverse_code=reverse_migration)
    ]
