# Generated by Django 3.1.14 on 2025-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=3),
        ),
    ]
