# Generated by Django 3.2.25 on 2026-08-10 16:20

from django.db import migrations, models
import django.db.models.deletion
import events.models.calendar
import events.models.event
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20250929_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='desktop_header_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.calendar.header_image_upload_location, validators=[events.validators.validate_calendar_desktop_header]),
        ),
        migrations.AddField(
            model_name='calendar',
            name='mobile_header_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.calendar.header_image_upload_location, validators=[events.validators.validate_calendar_mobile_header]),
        ),
        migrations.CreateModel(
            name='FeaturedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_feature_image', models.ImageField(upload_to=events.models.event.featured_image_upload_location, validators=[events.validators.validate_featured_event_desktop_image])),
                ('mobile_feature_image', models.ImageField(upload_to=events.models.event.featured_image_upload_location, validators=[events.validators.validate_featured_event_mobile_image])),
                ('alt_text', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='events.event')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
