# Generated by Django 3.2.25 on 2025-07-15 09:15

from django.db import migrations, models
import events.models.calendar


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20250529_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='desktop_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[events.models.calendar.validate_calendar_desktop_header_dimensions]),
        ),
        migrations.AddField(
            model_name='calendar',
            name='mobile_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[events.models.calendar.validate_calendar_mobile_header_dimensions]),
        ),
    ]
