# Generated by Django 3.2.25 on 2026-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_featuredevent_calendar_header_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
