# Generated by Django 3.2.25 on 2025-07-15 11:10

from django.db import migrations, models
import events.models.calendar


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20250715_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='desktop_header_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.calendar.header_image_upload_location, validators=[events.models.calendar.validate_calendar_desktop_header_dimensions]),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='mobile_header_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.calendar.header_image_upload_location, validators=[events.models.calendar.validate_calendar_mobile_header_dimensions]),
        ),
    ]
