# Generated by Django 3.2.25 on 2025-07-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20250715_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_feature_image', models.ImageField(upload_to='')),
                ('mobile_feature_image', models.ImageField(upload_to='')),
                ('start_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='events.event')),
            ],
        ),
    ]
