# Generated by Django 3.2.25 on 2025-07-21 12:03

from django.db import migrations, models
import events.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_featuredevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredevent',
            name='desktop_feature_image',
            field=models.ImageField(upload_to=events.models.event.featured_image_upload_location),
        ),
        migrations.AlterField(
            model_name='featuredevent',
            name='mobile_feature_image',
            field=models.ImageField(upload_to=events.models.event.featured_image_upload_location),
        ),
    ]
