# Generated by Django 3.2.25 on 2025-07-22 05:07

from django.db import migrations, models
import events.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20250721_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredevent',
            name='desktop_feature_image',
            field=models.ImageField(upload_to=events.models.event.featured_image_upload_location, validators=[events.models.event.validate_feature_event_desktop_dimensions]),
        ),
        migrations.AlterField(
            model_name='featuredevent',
            name='mobile_feature_image',
            field=models.ImageField(upload_to=events.models.event.featured_image_upload_location, validators=[events.models.event.validate_feature_event_mobile_dimensions]),
        ),
    ]
