# Generated by Django 3.2.25 on 2025-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlrelatedevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
