# Generated by Django 3.1.14 on 2022-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoanchor',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
