# Generated by Django 3.1.14 on 2022-11-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auto_20221116_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('imported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='seo.internallink')),
            ],
        ),
        migrations.DeleteModel(
            name='AutoAnchor',
        ),
    ]
