# Generated by Django 3.1.14 on 2022-11-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_internal_link_checked'),
        ('seo', '0005_auto_20221117_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLinkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_link_replacements', to='events.event')),
                ('internal_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_records', to='seo.internallink')),
                ('keyword_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='seo.keywordphrase')),
            ],
        ),
    ]
