# Generated by Django 3.1.14 on 2022-11-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_internallinkrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internallinkrecord',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
